version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - docker build -t pthomas-fargate:latest .
      - docker tag pthomas-fargate:latest 919821368124.dkr.ecr.us-east-1.amazonaws.com/pthomas-fargate:latest
  post_build:
    commands:
      - docker push 919821368124.dkr.ecr.us-east-1.amazonaws.com/pthomas-fargate:latest
      - printf '[{"name":helloworld,"imageUri":"%s"}]' 
       919821368124.dkr.ecr.us-east-1.amazonaws.com/pthomas-fargate:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
